### ISSUE TITLE
emacs tramp mode does not respect .clang-format in the remote directory

### ISSUE THREAD

**Issue by concretevitamin** [emacsorphanage/clang-format#1]
(This is a cross-post from https://stackoverflow.com/questions/48678302/emacs-tramp-mode-does-not-respect-clang-format-in-the-remote-directory.)

I have a git repo with a `.clang-format` and a `simple.c` source code. In local mode, namely editing off local disk, it respects the style file. However if I edit using tramp mode the same repo, then `clang-format` will format the source code using some default style file (I don't know where it's picked up), and will NOT honor the style file existing in the same remote directory. 

Q1: How do I fix this?

Q2: (Maybe it's easier) Where does clang-format in tramp-mode pick up the style file by default?

**Comment by tarsius** [comment]
This is only a mirror. Please contact upstream instead.

In this case that unfortunately mean writing to some `llvm` mailing list and hoping that the responsible person reads it. If you do get in contact with a maintainer, then please also suggest that they put a contact email in the header and maybe even move the elisp libraries into a separate (git) repository.
